export const paths = {
	home: '/',
	signIn: '/sign-in',
	map: '/map',
	favoriteClients: '/favorite-clients',
	profile: '/user/:userId',
	settingsProfile: '/settings/profile',
	settingsContracts: '/settings/contracts',
	settingsSubscribesRegions: '/settings/subscribes/regions',
	settingsSubscribesClients: '/settings/subscribes/clients',
	clientProfile: '/client/:clientId',
	mapPlayGround: '/map-play-ground',
	meetingDetails: '/meeting-details/:meetingId',
	meetingDetailsMobile: '/meeting-details-mobile',
	clientBusinessPointMobile: '/client-business-point-mobile/:clientId',
	managersSales: '/managers-sales',
	error: '/error',
	noMatch: '*',
}

export const routes = {
	home: () => paths.home,
	signIn: () => paths.signIn,
	map: () => paths.map,
	favoriteClients: () => paths.favoriteClients,
	profile: ({ userId }: { userId: string }) => paths.profile.replace(':userId', userId),
	settingsProfile: () => paths.settingsProfile,
	settingsContracts: () => paths.settingsContracts,
	settingsSubscribesRegions: () => paths.settingsSubscribesRegions,
	settingsSubscribesClients: () => paths.settingsSubscribesClients,
	clientProfile: ({ clientId }: { clientId: string }) => paths.clientProfile.replace(':clientId', clientId),
	meetingDetails: ({ meetingId }: { meetingId: string }) => paths.meetingDetails.replace(':meetingId', meetingId),
	meetingDetailsMobile: ({ meetingId, userId }: { meetingId: string; userId: string }) => paths.meetingDetails,
	clientBusinessPointMobile: ({ clientId }: { clientId: string }) =>
		paths.clientBusinessPointMobile.replace(':clientId', clientId),
	managerSales: () => paths.managersSales,
	error: () => paths.error,
	mapPlayGround: () => paths.mapPlayGround,
}
